--Creación de la Base de Datos
CREATE DATABASE TSQL2022
ON
   PRIMARY (NAME = TSQL2022_DAT,
   FILENAME = 'D:\SQLData\TSQL2022_DATA.MDF',
   SIZE = 50,
   MAXSIZE = 250,
   FILEGROWTH = 50%)
   LOG ON ( NAME = TSQL2022_LOG,
   FILENAME = 'D:\SQLLog\TSQL2022_LOG.LDF',
   SIZE = 25,
   MAXSIZE = UNLIMITED,
   FILEGROWTH = 10)
GO
