----query
----sql
---query de creacion de una tabla 
----sintaxis para crear unha tabla sql server
create table t0_cliente
(cod_cliente int,
nombre varchar (150),
apellido varchar(150),
fecha_nacimiento date,
edad int,
sueldo decimal(18,2))

---consultar una tabla
----transact sql ---select  ---insert   ---update ---delete

select*
from t_cliente

------------------------------
-------transact sql 
--------------------------------------DDL LENGUAJE DE DEFINICION DE OBJETOS 
---CREATE, DROP, ALTER
----TABLE 
-----CREATE 
---CREAR TABLA
 CREATE TABLE T_PERSONA
 (NOMBRE VARCHAR(150),
 APELLIDO VARCHAR(150),
 EDAD INT,
 FEC_NACIMIENTO DATE
 )

 ----DROP 
 ---ELIMINAR TABLAS

 DROP TABLE t0_cliente

 ----ALTER

----1.- AGREGAR UN NUEVO CAMPO A LA TABLA
ALTER TABLE T_PERSONA
ADD SUELDO DECIMAL(18,4)
----2.- ELIMINAR UN CAMPO 
ALTER TABLE T_PERSONA
DROP COLUMN SUELDO 
-----3.-CAMBIAR EL TIPO DE DATO DE LA COLUMNA 

ALTER TABLE T_PERSONA
ALTER COLUMN SUELDO DECIMAL(18,4)

----------------------------------DML LENGUNAJE DE MATIPULACION DE OBJETOS 
----INSERT---INSERTAR REGISTROS DENTRO DE LAS TABLAS
CREATE TABLE CURSO2(
IDCURSO INT,
NOMBRE_CURSO VARCHAR(150)
)

SELECT *
FROM CURSO2

---SINTAXIS

INSERT INTO CURSO2
(IDCURSO,NOMBRE_CURSO)
VALUES(1,'MATEMATICAS1')

INSERT INTO CURSO2
(IDCURSO,NOMBRE_CURSO)
VALUES(2,'MATEMATICAS2')

INSERT INTO CURSO2
(IDCURSO,NOMBRE_CURSO)
VALUES(3,'MATEMATICAS3')

--DELETE

---ME PERMITE ELIMINAR LOS REGISTROS DE UNA TABLA	
DELETE FROM CURSO2

----SELECCIONAR LA INFORMACION A BORRAR

SELECT *
FROM CURSO2
WHERE IDCURSO=2

----BORRAR LA INFORMACION APLICANDO EL FILTRO

DELETE FROM CURSO2
WHERE IDCURSO=2

--UPDATE
----PARA ACTUALIZAR UN REGISTRO DE LA TABLA 
----SINTAXIS

UPDATE CURSO2
SET NOMBRE_CURSO='ALGORITMO'
DROP TABLE CURSO2 
SELECT *
FROM CURSO2

---1.-Identificar los registros ha ser actualizados 

SELECT *
FROM CURSO2
WHERE IDCURSO=2

----2.-UPDATE A LA TABLA, AÑADIR EL WHERE DE LOS REGISTROS HA SER ACTUALIZADOS  

UPDATE CURSO2
SET NOMBRE_CURSO='ALGORITMO'
WHERE IDCURSO=2

SELECT *
FROM CURSO2
WHERE IDCURSO=1 OR IDCURSO=2
---ACTUALIZAR DOS O MAS CAMPOS 
UPDATE CURSO2
SET IDCURSO=5, NOMBRE_CURSO='MATEMATICAS'
WHERE IDCURSO=1 OR IDCURSO=2
	--INSERT INTO CURSO2
	--(IDCURSO,NOMBRE_CURSO)
	--VALUES(2,'MATEMATICAS2')